name: Flutter iOS Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_ios:
    name: Build Flutter iOS (.ipa)
    runs-on: macos-latest

    steps:
      # 1️⃣ Récupérer ton code source
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Installer Flutter manuellement (version compatible Dart 3.8)
      - name: Force install Flutter 3.35.7
        run: |
          git clone https://github.com/flutter/flutter.git --branch 3.35.7 --depth 1
          echo "$PWD/flutter/bin" >> $GITHUB_PATH
          flutter --version

      # 3️⃣ Télécharger les dépendances
      - name: Flutter Pub Get
        run: flutter pub get

      # 4️⃣ Préparer le projet iOS (génère Generated.xcconfig)
      - name: Prebuild iOS files
        run: flutter build ios --no-codesign

      # 5️⃣ Installer CocoaPods (pour dépendances Swift/Obj-C)
      - name: Install CocoaPods
        run: |
          cd ios
          pod install --repo-update
          cd ..

      # 6️⃣ Construire le fichier .ipa (non signé)
      - name: Build iOS release (.ipa)
        run: flutter build ipa --release --no-codesign

      # 7️⃣ Uploader le .ipa en artifact (téléchargeable)
      - name: Upload iOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-release
          path: build/ios/ipa/
